# Generated by Django 5.2.5 on 2025-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gpay_qr',
            field=models.ImageField(blank=True, null=True, upload_to='gpay_qr/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
