# Generated by Django 5.2.5 on 2025-09-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.userprofile'),
        ),
    ]
