# Generated by Django 5.2.5 on 2025-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_book_alter_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gpay_number',
            field=models.CharField(blank=True, help_text='Your Google Pay linked mobile number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Your UPI ID (e.g., name@upi)', max_length=50, null=True),
        ),
    ]
