# Generated by Django 5.2.5 on 2025-09-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_gpay_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='offered_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_swaps', to='core.book'),
        ),
    ]
