# Generated by Django 5.2.5 on 2025-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_swaprequest_offered_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GPay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('Other', 'Other')], default='GPay', max_length=50),
        ),
    ]
