# Generated by Django 5.2.5 on 2025-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gpay_number',
            field=models.CharField(blank=True, help_text='Google Pay linked mobile number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gpay_qr',
            field=models.ImageField(blank=True, help_text='Upload your Google Pay QR code', null=True, upload_to='gpay_qr/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.CharField(blank=True, help_text="User's city or place", max_length=100, null=True),
        ),
    ]
