# Generated by Django 5.2.5 on 2025-09-18 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(blank=True, help_text='The book being purchased.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(help_text='The user who is buying the book.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment record was created.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GPay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('Other', 'Other')], default='GPay', help_text='Payment method used by the buyer.', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional screenshot of the payment for verification.', null=True, upload_to='payments/screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(help_text='The profile of the user selling the book.', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', help_text='Current verification status of the payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction ID provided by the payment platform.', max_length=100, null=True),
        ),
    ]
