# Generated by Django 5.2.5 on 2025-09-18 17:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='book',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GPay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('Other', 'Other')], default='GPay', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total amount paid for the book.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(help_text='The book involved in this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(help_text='The user who is buying the book.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions_purchased', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction was created.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(help_text='The user who is selling the book.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', help_text='Current status of the transaction.', max_length=10),
        ),
    ]
