# Generated by Django 5.2.5 on 2025-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sale_book_sale_buyer_sale_seller_sale_swap_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
