# Generated by Django 5.2.5 on 2025-09-20 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sale_buyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile',
            field=models.CharField(blank=True, help_text="Buyer's mobile number for seller contact", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Book being purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GPay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('Other', 'Other')], default='GPay', help_text='Selected payment method', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional payment screenshot', null=True, upload_to='payments/screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(help_text='Seller (UserProfile) receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', help_text='Current status of the payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID / UPI reference', max_length=100, null=True),
        ),
    ]
