# Generated by Django 5.2.5 on 2025-09-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_payment_mobile_alter_payment_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
