# Generated by Django 5.2.5 on 2025-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_swaprequest_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Requester's mobile number for contact", max_length=15, null=True),
        ),
    ]
