# Generated by Django 5.2.7 on 2025-10-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_swaprequest_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
